"""replace id by slug

Revision ID: 74efe208391f
Revises: aacfb83cc363
Create Date: 2025-06-23 13:11:49.528771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74efe208391f'
down_revision: Union[str, None] = 'aacfb83cc363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('user_slug', sa.String(), nullable=False))
    op.add_column('doctor', sa.Column('hospital_slug', sa.String(), nullable=False))
    op.drop_constraint(op.f('doctor_user_id_fkey'), 'doctor', type_='foreignkey')
    op.drop_constraint(op.f('doctor_hospital_id_fkey'), 'doctor', type_='foreignkey')
    op.create_foreign_key(None, 'doctor', 'hospital', ['hospital_slug'], ['slug'])
    op.create_foreign_key(None, 'doctor', 'user', ['user_slug'], ['slug'])
    op.drop_column('doctor', 'hospital_id')
    op.drop_column('doctor', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('doctor', sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_hospital_id_fkey'), 'doctor', 'hospital', ['hospital_id'], ['id'])
    op.create_foreign_key(op.f('doctor_user_id_fkey'), 'doctor', 'user', ['user_id'], ['id'])
    op.drop_column('doctor', 'hospital_slug')
    op.drop_column('doctor', 'user_slug')
    # ### end Alembic commands ###
